apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jira-backup.fullname" . }}
  labels:
    {{- include "jira-backup.labels" . | nindent 4 }}
type: Opaque
data:
  site: {{ .Values.settings.site | b64enc | quote }}
  user: {{ .Values.settings.user | b64enc | quote }}
  token: {{ .Values.settings.token | b64enc | quote }}
  aws_access_key_id: {{ .Values.settings.s3.AWSAccessKeyID | b64enc | quote }}
  aws_secret_access_key: {{ .Values.settings.s3.AWSSecretAccessKey | b64enc | quote }}
  bucket_name: {{ .Values.settings.s3.bucketName | b64enc | quote  }}